// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7661-E839Qr_MKrSLK2Uf4GdMgqw7lfg',
    appId: '1:162588745678:web:3cf325534657e4be5dd59f',
    messagingSenderId: '162588745678',
    projectId: 'orbyt-template',
    authDomain: 'orbyt-template.firebaseapp.com',
    storageBucket: 'orbyt-template.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJJO5an2mYRTsq_glZtK4srqERydB13Bs',
    appId: '1:162588745678:android:bf14fee65be2941b5dd59f',
    messagingSenderId: '162588745678',
    projectId: 'orbyt-template',
    storageBucket: 'orbyt-template.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMFx-Vm2u7z2cHlXRDre5RCIRd435HQ6Y',
    appId: '1:162588745678:ios:4cd5fee299037a735dd59f',
    messagingSenderId: '162588745678',
    projectId: 'orbyt-template',
    storageBucket: 'orbyt-template.firebasestorage.app',
    iosBundleId: 'com.example.orbytTemplate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMFx-Vm2u7z2cHlXRDre5RCIRd435HQ6Y',
    appId: '1:162588745678:ios:4cd5fee299037a735dd59f',
    messagingSenderId: '162588745678',
    projectId: 'orbyt-template',
    storageBucket: 'orbyt-template.firebasestorage.app',
    iosBundleId: 'com.example.orbytTemplate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7661-E839Qr_MKrSLK2Uf4GdMgqw7lfg',
    appId: '1:162588745678:web:15b40a40c7c7cbdf5dd59f',
    messagingSenderId: '162588745678',
    projectId: 'orbyt-template',
    authDomain: 'orbyt-template.firebaseapp.com',
    storageBucket: 'orbyt-template.firebasestorage.app',
  );
}
